# Generated by Django 2.2 on 2020-10-14 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('The_Wall_Posts_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='user_likes',
            field=models.ManyToManyField(related_name='liked_posts', to='The_Wall_Posts_App.User'),
        ),
    ]
